
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_DATA = 'USER_DATA';
export const USER_PERMISSIONS = 'USER_PERMISSIONS';
export const ORGANIZATION_DATA = 'ORGANIZATION_DATA';
